### ISSUE TITLE
Giving talks - tedx and education

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#15]
# It's important that people find out about our projects, some people are only reachable in person. 
We had two stands for White Water Writers at exhibitions  in the last 15 months, BETT and NATE - neither of which were particularly postitive (althought BETT covered it's costs convincingly, it was with a single order and I feel like we got lucky). 

This isn't because we're bad at trade shows (I pride myself I'm pretty good), but I think we were in the wrong place - we don't belong with the stands that give out free pens.  

Everything we do is based on solid research and most of it *is* some sort of research.  When we were at NATE we should have been giving a talk rather than waiting for people by the coffee.   (we demonstrated our value at the MIX conference pretty well. 

So, this task is about finding places to give talks about our work. 

- [x] Find/make a list of at least 10 teacher/secondary education conferences that have speakers (preferably with researchers)  (to be clear, NOT academic conference, we have NO problem with those, we want professional conferences that like to hear from academics) 
- [x] Find/make a list of at least 10 teacher/secondary education conferences that have speakers (preferably with researchers) 
- [x] Make a list of the UK TEDx events happening between September (because the ealier ones will have been completely booked up) and the following march), along with their websites and contact emails. 

This is probably about 2 hours work, if it gets much longer than that let me know.

**Comment by WhiteWaterLMB** [comment]
**Teacher Conferences**

- [Teach First](https://www.teachfirst.org.uk/teacher-development-conference-2018) - Leeds (was 23rd-24th July, but seems annual)
- [BERA annual conference](https://www.bera.ac.uk/event/bera-conference-2018) - educational research - Northumbria University, Newcastle (10th September)
- [ACRE 2018](https://www.edgehill.ac.uk/education/research-education/conference-2018/) on critical issues in socially just research and practice - Edge Hill University, Lancashire
- [Warwick University](https://warwick.ac.uk/services/ldc/teaching_learning/conference_2018/) - involves Cultural and Creative Learning
- [ CTSN research conference](http://www.camteach.org.uk/160/ctsn-research-conference) (involves workshops - could be interesting?)
- [UCL, London (passed again, but annual)](https://www.ucl.ac.uk/teaching-learning/news-events/ucl-education-conference/ucl-education-conference-2018)
- [Higher education conference ](https://heconference.co.uk/)/ exhibition - involves a focus on collaboration, and I thought might work, due to links with Keele etc. and the student volunteers also learning?
- [Education show, NEC](https://www.education-show.com/) on teaching with creativity (March)
- [ Research and innovation in universities](https://www.universitiesuk.ac.uk/events/Pages/research-and-innovation-2018.aspx), Woburn House (16th October)
- [LICE (London International Conference on Education)](http://liceducation.com/) - includes imaginative education, language education, writing education, reseach and academic joint programmes, technology in education and education-research links. (10th-13th December)
- [Nine Worlds](https://nineworlds.co.uk/) (?) - not education-based, but creative and could possibly help with obtaining fiction licenses?

**TedX Events**

- Woking, Nov 3rd
- Brighton, Oct 26th
- Rotherhithe, Oct 13th
- Square Mile, Oct 20th
- Covent Garden Salon, Oct 12th
- Torquay, Sep 29th
- Truro, Oct 26th
- Wolverhampton, Nov 9th
- Lemmington Spa, Oct 13th
- Leicester, Sep 15th
- Sheffield, Oct 13th
- Lincoln, Nov 9th
- Hull, Sep 22nd
- Hessle, Sep 11th
- University of Bolton, Nov 7th
- Newcastle, Oct 6th

**Comment by joereddington** [comment]
I've removed the september ones. 
- [x]    Woking, Nov 3rd, emailed
- [ ]    Brighton, Oct 26th - definately fully booked. 
- [x]    Rotherhithe, Oct 13th
- [ ]    Square Mile, Oct 20th - definately closed. 
- [ ]    Covent Garden Salon, Oct 12th
- [ ]    Wolverhampton, Nov 9th (doesn't appear to exist online. 
- [ ]    Lemmington Spa, Oct 13th
- [ ]    Sheffield, Oct 13th
- [ ]    Lincoln, Nov 9th
- [ ]    University of Bolton, Nov 7th
- [ ]    Newcastle, Oct 6th

We'll find out if those ones email - but looking at the dates of closure for the TEDx's it might be worth looking at December/January. 

Next action is to do the same set of emails but for the school conferences.
