### ISSUE TITLE
Apply for Social Tech Fund by 24th July

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#18]
This is a really exciting fund that is perfect for the Open Voice Factory (particularly since the Social Tech Fund is the 'new version' of the Nominet Trust, who gave OVF some awards before they closed.  

# Resources
* [Application Website](https://socialtechtrust.org/investing/apply-for-investment/) 
* [The 90 second video I made](https://youtu.be/mleIuigwmdo) 

I've (Joe) registered with my eQT email address and "An activation email has been sent to your email address" 

# Plan 
- [x] Go through the goals of the funder and work out which of the projects are best suited to it.  
- [x] find out if you can apply with more than one project 
- [x] Write 50 words. 
- [x] do some copy paste from previous applications 
- [x] Draft the application 
- [x] put through simplewriter 
- [ ] ask for comments (ran out of time)

**Comment by joereddington-public** [comment]
###### 10/07/18 12:38 to 12:51
Approved account by email last night. 

Turns out it's only 50 words....

> What is the name of your project? * 
> This could be the same name as your venture. You can change this at any time before you submit your application.
> Please provide a brief summary of your project * 
> 50 words remaining
> 
> You can change this at any time before you submit your application.

I've made some notes from the website to try and highlight the language the funder uses:
 
* "It aims to demonstrate how tech can reach its transformative potential when it’s driven by one of the greatest opportunities of our time – equality."
* "This is a call for radical new approaches that shift the balance of ‘power to people and communities‘ who want to challenge an unequal status quo. Tech is increasingly called upon to drive these shifts . . . but more radical and powerful still, is to look to people and communities to drive tech to unite us." 
* "We’ll grant fund up to 10 ambitious ventures" 
* "Evidence of your potential to create user, social and financial value; for example, a theory of change, user co-design and testing, identified social KPIs, or prospective partnerships or routes to market." 
* "in-house tech capabilities being an essential." 
* "The 90 second video is a chance for your team to “pitch” your innovation, and for us to get to know your team, so please make sure your team appears in it " 
* No core costs 

###### 12:51: 
I've tweeted the question about multiple projects, I feel like they want to fund something like the OVF, but I also feel like Supertitle would benefit most from some funding (although, that mostly wants 'scaling' funding.  Hmmm.

**Comment by joereddington** [comment]
I think a 90 second version of this video would work well: https://www.youtube.com/watch?v=tF4kYd6TEZc

**Comment by joereddington** [comment]
I've edited it down: https://youtu.be/mleIuigwmdo

**Comment by joereddington-public** [comment]
###### 20/07/18 16:11: 
Started application today and found out there is quite a lot more to it  after filling in the 50 words.  

I've started putting together a word document of the questions - it's here: [Tech to Unite Us Application.docx](https://github.com/eQualityTime/Public/files/2214455/Tech.to.Unite.Us.Application.docx).

**Comment by joereddington** [comment]
I need to phone and ask about the difference between 'our solution' and 'our technology'

**Comment by joereddington-public** [comment]
I phoned: 'Our solution' is for the casual reader who doesn't know about technology, 'our technology' is for a programmer.

**Comment by joereddington-public** [comment]
I've done some work on the document [Tech.to.Unite.Us.Application v.02.docx](https://github.com/eQualityTime/Public/files/2224130/Tech.to.Unite.Us.Application.v.02.docx)

**Comment by joereddington-public** [comment]
![screen shot 2018-07-30 at 16 40 54](https://user-images.githubusercontent.com/40637406/43408100-6104c55c-9418-11e8-833b-f0ea56b2b8ba.png)


Submitted!
