### ISSUE TITLE
Run your weekly social media process four times

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#21]
# Summary 
We do cool projects and we should tell people about them so that they either engage with the project as a user, or they help it grow. 

## Edit
Really want to start promoting our books. 

# Resources 
* Hootsuite (for facebook)
* Buffer (for twitter)  ( you can sign in with either of the twitter accounts or with joe.reddington@gmail.com) 

# Problem 
Not everybody thinks like we do, and wants to be engaged  the same way. So we must make sure that our output covers all of the people who are interested in our work. 

# Plan 
- [x] work out some user profiles 
- [ ] identify some (genuine) content they might like, 
- [ ] Put it into a social media calendar. 
- [ ] assess after a week.

**Comment by joereddington** [comment]
# User profile draft. 

## Long term objectives 
Being transparent is its own reward - the more work we can share the more we are likely to do our work properly.
We also want to raise our public profile and build connections with people who can help us. 

## Short term objectives
None.  We aren't interested in short-term spikes such as likes and going viral.  Joe's been viral, it didn't help. (Example - Flowers for Turing got around 10k retweets in its first year, and raised about £80. Last year it raised about £1600 and got about 500 mentions).  

# Target Audience
There are seven people we want to contact with our social media. This list is written for White Water Writers, but the same characters are relevent for Supertitle and Open Voice Factory (teacher becomes an SLT, the student studies Computer Science, and the writer is a manufacturer). We want to make sure that we are talking to each of them with our output.  

(all names (and hence genders and ethnicities) generated randomly by https://www.name-generator.org.uk/quick/) 

## Fraser 
Fraser is 15, has done a White Water Writer camp, he is proud of it and wants to do it again. We want to remind him regularly of how much fun it was. Fraser is into Facebook and Instragram. 

## Amy-Leigh
Amy-Leigh is a 30-year old teacher, she cares about her students and wants them to have cool oppertuntities.  She is wary of outside interventions because they overpromise and under deliver. We want to show her how our approaches work and resolve any fears she might have about getting invovled.  Amy-Leigh's social media is very locked down, but she does have a Twitter account and occasionally looks at Facebook.    

## George
George is a 20 year old English student who believes in changing the world. He's looking for a cool new *thing* to talk about. He's on Facebook and Instagram. 

## Steve 
Nayan is a 36-year old failed writer who thinks that you CAN'T mechanise creativity.  We want to change his mind.  He's mostly on Twitter but also willing to rant on Facebook. 

## Nate
Nate is a journalist.  He's interested good photos, clicks and the number of likes something has.  He's a Twitter person and occasionally responds to email, but is more likely to write about whatever is getting good reddit traction that day.  

## Janet the Funder
JTF is an old-school (and old, school) funder. She doesn't understand technology but decides what to fund based on how much smart people talk about it.  (obviously this doesn't include any of our current (2018) funders, because they all understand technology).  Janet reads what Nate writer and is willing to have a Google.  (Janet also includes headteachers and politicians)

## Saqib
Saqib, is 24 and works for us as a member of staff.  They know their job, but they are also interested in how we are changing internally, and policy updates, and in new features on our projects.   

# Platforms 
More networks is more hassle.  We concentrate on Facebook and Twitter for 'brands' and Reddit for pushing individual events.

**Comment by joereddington-public** [comment]
- I don't want to start with the user profiles, I want to start with the information.  
- We list the changes that have happened in the week (or will happen)
- For each of them we look at who cares, and tailor the copy/platform to them
- then we look at the missing user profiles and think about what they might like to see.

**Comment by joereddington-public** [comment]
News this week. 

* Hired a researcher  
* Signed off the comic relief document 
* Hired an accountant 
* (future) a set of policies for medical device developing 
* We'll be represented at CM 
* Done some streaming....
* Moved to amazon business. 

Next todo is to go through those and work out who cares.  Some of them need blogging.

**Comment by joereddington-public** [comment]
Let's look at each in turn. 

# Fraiser
* Signed off the comic relief document 
* Done some streaming....


# Amy-Leight
* Hired a researcher  
* (future) a set of policies for medical device developing 
* We'll be represented at CM 

# George 
* Signed off the comic relief document 
* Done some streaming....
* Moved to amazon business. 

# Steve 
* Hired a researcher  
* (future) a set of policies for medical device developing 
* Done some streaming....

# Nate 
* Hired a researcher  
* (future) a set of policies for medical device developing 
* Done some streaming....

# Janet 
* Hired a researcher  
* Signed off the comic relief document 
* Hired an accountant 
* (future) a set of policies for medical device developing 
* Moved to amazon business.  (professionalisation) 


# Saqib
* Hired a researcher
* Signed off the comic relief document
* Hired an accountant
* ( future) a set of policies for medical device developing
* We'll be represented at CM
* Done some streaming....
* Moved to amazon business.

## So 

Hired a researher! 

### Facebook
Aideen has joined eQuality Time as a researcher: she's in charge of producing a communication board for Dementia for the Essex challenge prize. She comes extremely highly recommended and it's important she is - we're a research based organisation and we need to know that we're building on a rock solid base and so do the people who trust us.  Really looking forward to seeing what she produces. 

### Twitter 
We've hired a researcher! Aideen will be in charge of producing a communcation board for users with Dementia as part of the #Essexchallengeprize.  



# Signed off the comic relief document
eQuality Time is going places! We've signed out our Comic Relief funding deal for £45,000. Feels like a big, but exciting responsibility.  One of the hardest things to do is force yourself to look at the fine print when a funding is offering you your dream. But it's really important, particularly if you are going to have a good relationship with the funder. 



# Done some streaming
Write a blog. 

# Moved to Amazon Business. 
Some internal changes - White Water Writers is growing so that means our internal systems have to grow as well. We've moved over to Amazon business for our book orders on the basis that we're ordering a amazingly large number of books in a week, and, more importantly, for a range of different organisations, leaders, and funders.  Fair warning, if you lead a lot of camps you are probably going to be given the responsibility for ordering the books as well. 


'lnn
Now to write a blog.

**Comment by joereddington-public** [comment]
###### 30/07/18 17:09: 
Did three blog posts and some promotion of  books today.

**Comment by joereddington** [comment]
I had forgotten how much work I'd put into this, it need some adjustment to the title and so on.
