### ISSUE TITLE
Apply for Children In Need with Supertitle 11:59pm 13 September 2018

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#39]
We're applying to [Children in Need](http://www.bbc.co.uk/programmes/articles/3XW7FvN20PD3xr2c1T62Xly/main-grants), with the [Supertitle](http://equalitytime.co.uk/supertitle/) project.  

# Resources 
* A previous application form is [here](http://equalitytime.co.uk/wp-content/uploads/2016/03/Small-Grants-Application-Form-from-Sept-2015.pdf) 
* The main application login page is [here](https://www.grantrequest.co.uk/Login.aspx?ReturnUrl=%2faccountmanager.aspx%3fSA%3dAM%26sid%3d107&SA=AM&sid=107)
* Created an account with 'joe@equalitytime.co.uk' - probably should have used 'admin@'

- [x] read http://equalitytime.co.uk/5768/2016/04/01/children-in-need-interview/
- [x] register with website 
- [x] get the full set of questions from the website 
- [x] Answer the remaining question from [this post](http://equalitytime.co.uk/5903/2016/09/05/supertitle-phase-2-report/)
- [x] Copy Budget accross to public. 
- [x] fill out and submit form. 

# Summary
This application wasn't our best work and it doesn't do justice to the project - but the deadline snuck up on us and it's better to have put it through than to have missed it.  I'd like to do a comprehensive rewrite of it. If we get rejected then that will be my chance!

**Comment by joereddington-public** [comment]
Next Action is to register with the website: the application form is [here](https://www.grantrequest.co.uk/Login.aspx?ReturnUrl=%2faccountmanager.aspx%3fSA%3dAM%26sid%3d107&SA=AM&sid=107)

**Comment by joereddington** [comment]
[childreninneed.pdf](https://github.com/eQualityTime/Public/files/2378942/childreninneed.pdf)

**Comment by joereddington-public** [comment]
Some notes from the A-Z

* "If you have a website or allow the children and young people to use computers or the internet from your building, we will ask you about your ‘acceptable usage policy’." 
* "We do not adopt the full cost recovery model. We will not fund any overheads relating to the wider organisation, and will only fund direct project costs." 
* "We define mentoring or befriending as a *formal and structured arrangement* [emphasis mine] which is “a voluntary, mutually beneficial and purposeful relationship in which an individual gives time to support another to enable them to make changes in their life”."
* "The reserves policy should state:

    how much the organisation needs to hold in reserve and why
    how and when the organisation’s reserves can be spent
    how often the reserves policy will be reviewed"

* "We expect projects to take place before or after school, during lunch or in the holidays. "
* "We expect projects to focus on addressing issues of disadvantage affecting children and young people. We define disadvantage as: Illness, distress, abuse or neglect; Any kind of disability; Behavioural or psychological difficulties; Living in poverty or situations of deprivation."

**Comment by joereddington-public** [comment]
### Please describe the disadvantages experienced by the children and young people you work with, and how they are affected.  
*from previous application* 

Please describe the disadvantages experienced by the children and young people you work with, and how they are affected.
We work with children with English as an Additional Language (EAL). This group of children, many of whom are child migrants, are at a great disadvantage within the UK system. 
They are disadvantaged first by their use of language "Bright children from migrant backgrounds are routinely placed in classes for low ability pupils because bilingualism is still wrongly associated with special educational needs " (http://www.ioe.ac.uk/56528.html). 
Secondly, they are more likely to live in the most disadvantaged areas. An OCED report in 2012 found that EAL children are more than twice as likely to attend disadvantaged schools as their non¬ immigrant counterparts" (http://www.oecd.org/edu/eag2012.htm). 
As well as disadvantages in the school system. EAL children face many social pressures. EAL children in the UK can feel distanced from their cultural /religious heritage. Many are at a time in their life when they may be searching for answers to questions about identity, faith and belonging. This can cause problems from attendance to a risk of a complete rejection of one or both cultures. 
As a result, many bilingual secondary children identify themselves as monolingual. Their experience is that their home languages are of little value in the education system (http://www.ioe.ac.uk/56528.html). 

(200 words) 

### Please describe the activities or services you are asking us to fund.  
(200 words) 

We run translation 'Supertitle' clubs for groups of young people who have English as an Additional Language. Schools typically put EAL children in special classes to fix their English, which can make them feel marginalised and ashamed. SuperTitle clubs use popular culture as a medium through which children can make their language skills better without feeling looked down on.
Each group meets once a week after school to translate the subtitles for their choice of TV show. Once the subtitles have been translated, students are encouraged to share the TV show with the families. In this way, Supertitle supports children to be a bridge between communities rather than feeling they have to choose a 'side'.
We would like Children in Need to fund the cost of starting Supertitle groups in 100 schools across London and Luton. 


### Please briefly describe the first difference your project will make in children and young people's lives 
(50 words)
English Language Skills


### Please describe how the activities or services you provide will bring about this first difference.
(200 words) 

Children in a Supertitle group spend a full hour at each meeting working on translation. As they work, they look at the English text very carefully to break it down by meaning. When working they talk to each other to make sure of meanings and understand what is being said and why it is being said. This sort of careful deep learning is very hard to create in a school, but Supertitle is set up so that this learning of language happens 'for free'.


### Please briefly describe the second difference your project will make in children and young people's lives 
(50 words)
Increasing the 'cultural confidence' of children 

### Please describe how the activities or services you provide will bring about this second difference.
(200 word) 

EAL children in the UK school system can feel distanced from they cultural/religious heritage. As a result, many bilingual secondary school children identify themselves as monolingual. Their experience is that their home languages are of little value in the education system (http://www.ioe.ac.uk/56528.html).
EAL children in the UK school system can feel distanced from their cultural /religious heritage. Many are at a time in their life when they may be searching for answers to questions about identity, faith and belonging. This can cause problems from attendance to a risk of a complete rejection of one or both cultures.
Many of the children we work with have problems fitting in at school, and often think that they must choose between either being a British person or being part of their 'home' community. Supertitle helps these children to be a bridge between the two sides, rather than having to choose one. When children choose to make UK TV they are identifying a cultural product that resonates with them and are encouraged to share this with their home community. This empowers them to explore cultural differences and similarities in a safe, meaningful way.

### For  projects that are already running, previously funded by BBC Children in  Need or another funder, please briefly describe the differences your  project has achieved for children and young people to date, and describe  what evidence you have that your project made that difference.

We successfully piloted this project with the aid of a grant from Awards for All. This allowed us to run sessions in 10 schools so far, working with around 60 students in six languages and improving the cultural competance and english language skills of the students.
These are some of the comments from the students:


“I found this workshop fun and useful because you are helping people that
don’t understand it and need translating it. I am really happy that I was
able to take part in this session and I was able to use my skills to work
as a team”

Jessica


I found the workshop very useful because I worked well in a team and
it helped me writing with more confidence in Portuguese. Also, I have made
new friends. I have had really good fun”

Nicole 


“I found this session very useful because I practised my Portuguese and I
also know that by producing the subtitles I can help Portuguese people in
the UK to understand what they are watching. I found it really fun as well
as useful”

Tecia.


“I enjoyed this workshop as my family also face the struggle of not always
understanding shows and I am glad to give back to the community by helping
others who have the same problem.”

Mariana


I liked the work shop so much! It helped me improve my language skills. It
was really helpful and I would love to participate in future workshops.

Maria-Jose


(200 words)

**Comment by joereddington** [comment]
Children and Young People 
Please describe the disadvantages experienced by the children and young people you work with, and how they are affected.
We work with children with English as an Additional Language (EAL). This group of children, many of whom are child migrants, are at a great disadvantage within the UK system. 
They are disadvantaged first by their use of language "Bright children from migrant backgrounds are routinely placed in classes for low ability pupils because bilingualism is still wrongly associated with special educational needs " (http://www.ioe.ac.uk/56528.html). 
Secondly, they are more likely to live in the most disadvantaged areas. An OCED report in 2012 found that EAL children are more than twice as likely to attend disadvantaged schools as their non¬ immigrant counterparts" (http://www.oecd.org/edu/eag2012.htm). 
As well as disadvantages in the school system. EAL children face many social pressures. EAL children in the UK can feel distanced from their cultural /religious heritage. Many are at a time in their life when they may be searching for answers to questions about identity, faith and belonging. This can cause problems from attendance to a risk of a complete rejection of one or both cultures. 
As a result, many bilingual secondary children identify themselves as monolingual. Their experience is that their home languages are of little value in the education system (http://www.ioe.ac.uk/56528.html). 
Overall, how many disadvantaged children and young people will benefit from your project?
(Estimates are fine) 
Aged 0¬4 years Aged 5¬9 Aged 10¬15 Aged 16¬18 Total: 0 0 200 60 260 
How many children and young people in total will benefit from your project? 260 
Please describe the role children and young people play in planning and delivering your project. Once they have been set up, Supertitle groups are completely member¬led. Expected results such as 
Keeping Children Safe 
Does your organisation have its own child protection policy? Yes 
What is the name and job title of the person responsible for child protection in your organisation? Tess Reddington, Treasurer 
Do you make sure that all eligible staff, management committee and volunteers have Disclosure & Barring Service, Disclosure Scotland or Access NI checks?
Yes 
Please explain if not.
All staff that deal with the public, or any data held, have a DBS check. 
How often do you repeat Disclosure & Barring Service, Disclosure Scotland or Access NI checks? Your answer must not exceed 255 characters (including all punctuation and spaces).
yearly. 
Do you make sure that all staff and volunteers with access to children and young people, and all management committee members, attend child protection training?
Yes 
Please explain if not.
All staff that deal with the public, or any data held, must have attended child protection training. 
How often do staff, management committee and volunteers have their child protection training refreshed?
every three years 
Your Project 
English language development, increased confidence and self empowerment all come from the act of solving the translation problem rather than a 'directed learning' strategy. 
Group members choose the TV show to work on, share out the 'jobs' between themselves, and they work together to create their own translation conventions and 'house style'. Members will also be the main source of recruiting new members to their groups. 
Much of their discussion will naturally take place in the home language of the group and because we make sure that no adult present is familiar with that language, the young people are aware of, and empowered by, the trust placed in the group. 
The greater the role that the children and young people play in the project, the greater the benefits to them and their families. 
Your project 
Please describe the activities or services you are asking us to fund.
We run translation 'Supertitle' clubs for groups of young people who have English as an Additional Language. Schools typically put EAL children in special classes to fix their English, which can make them feel marginalised and ashamed. SuperTitle clubs use popular culture as a medium through which children can make their language skills better without feeling looked down on. 
Each group meets once a week after school to translate the subtitles for their choice of TV show. Once the subtitles have been translated, students are encouraged to share the TV show with the families. In this way, Supertitle supports children to be a bridge between communities rather than feeling they have to choose a 'side'. 
We would like Children in Need to fund the cost of starting 20 new groups and the cost of supporting the volunteers who run existing groups. 
Does your project or activity charge fees for participation or membership so that children and young people can attend?
If yes, please tick the box below.
No 
When will your project happen and how often? (Your answer must not exceed 255 characters including all punctuation and spaces).
This project phase begins in September 2016. Our clubs run weekly after the school day. However the support and setup costs are more regular. 
Will your project or activities take place during school hours? If yes, please tick the box below.
No 
Where will the activities take place? (Your answer must not exceed 255 characters including all punctuation and spaces).
Partipating school supply classrooms and computers. 
Which local authority or unitary authority areas is your project working in? Across London, concentrating in Camden and Merton 
Does your project include any of the following: residentials (an overnight stay), befriending or mentoring activity, counselling?
If yes, please tick the box below.
No 
The Difference You Will Make (Outcomes) 
The Difference Your Project Will Make 
Before answering the following questions about differences, please read the information on our website about how, together, we improve children's lives. 
Please describe the three most important differences your project will make in the lives of the children and young people you work with. 
	Please briefly describe the first difference your project will make in children and young people's lives. This can be a small step or a lasting change.
English Language Skills 
Please describe how the activities or services you provide will bring about this difference. Children in a Supertitle group spend a full hour at each meeting working on translation. As they work, they look at the English text very carefully to break it down by meaning. When working they talk to each other to make sure of meanings and understand what is being said and why it is being said. This sort of careful deep learning is very hard to create in a school, but Supertitle is set up so that this learning of language happens 'for free'. 
Please describe what information (such as statistics, feedback, observation etc) you will collect to measure how well this difference has been achieved
Researchers at Keele University have supported eQuality time to develop a pre¬post assessment for SuperTitle. This is in the form of a questionnaire that includes questions about children's English Language Skills (ELS) and cultural identity. If children provide their informed consent, we ask them to complete the questionnaire and the start and end of their group work. We will analyse the children's responses to the questionnaire after the group finishes to assess the degree to which their ELS have improved and identify positive changes in their cultural identity. In addition, we analyse the time taken to translate and the quality of the final TV show translation to assess changes in children's ELS during the project. 
Please briefly describe the second difference your project will make in children and young people's lives.
Increasing the 'cultural confidence' of children 
Please describe how the activities or services you provide will bring about this difference.
EAL children in the UK school system can feel distanced from they cultural/religious heritage. As a result, many bilingual secondary school children identify themselves as monolingual. Their experience is that their home languages are of little value in the education system (http://www.ioe.ac.uk/56528.html). 
EAL children in the UK school system can feel distanced from their cultural /religious heritage. Many are at a time in their life when they may be searching for answers to questions about identity, faith and belonging. This can cause problems from attendance to a risk of a complete rejection of one or both cultures. 
Many of the children we work with have problems fitting in at school, and often think that they must choose between either being a British person or being part of their 'home' community. Supertitle helps these children to be a bridge between the two sides, rather than having to choose one. When children choose to make UK TV they are identifying a cultural product that resonates with them and are encouraged to share this with their home community. This empowers them to explore cultural differences and similarities in a safe, meaningful way. 
Please describe what information (such as statistics, feedback, observation etc) you will collect to measure how well this difference has been achieved
Researchers at Keele University have supported eQuality time to develop a pre¬post assessment for SuperTitle. This is in the form of a questionnaire that includes questions about children's English Language Skills (ELS) and cultural identity. If children provide their informed consent, we ask them to complete the questionnaire and the start and end of their group work. We will analyse the children's responses to the questionnaire after the group finishes to assess the degree to which their ELS have improved and identify positive changes in their cultural identity. 
We will also be holding small group talks with a sample of the Supertitle groups using a facilitator

**Comment by joereddington** [comment]
Budget is in this file: 
[Budget.xlsx](https://github.com/eQualityTime/Public/files/2380964/Budget.xlsx)


The breakdown is:  


  | 18 month, two facilitators, 100   schools | Year 1 | Year 2 | Category
-- | -- | -- | -- | --
Accounting | £                                                                                          850.00 | £                      400.00 | £                 450.00 | Project costs
Equipment and other digital costs | £                                                                                       2,300.00 | £                   1,800.00 | £                 500.00 | Large   equipment (over £250)
Transport | £                                                                                          800.00 | £                      600.00 | £                 200.00 | Other staffing costs (recruitment/training/travel)
Facilitator costs 0.7FT (6 months) | £                                                                                       7,611.45 | £                   7,611.45 | £                         - | Salary   expenditure (including National Insurance and pension)
Facilitator costs 0.3FT (18 months) | £                                                                                       7,828.92 | £                   3,914.46 | £              3,914.46 | Salary   expenditure (including National Insurance and pension)
Project manager  0.4FT (18months) | £                                                                                     17,953.20 | £                   8,976.60 | £              8,976.60 | Salary   expenditure (including National Insurance and pension)
Publishing , Design, and online content   costs | £                                                                                       1,200.00 | £                      400.00 | £                 800.00 | Project costs
Insurance, subscriptions and resources   such as books | £                                                                                          440.00 | £                      220.00 | £                 220.00 | Project costs
Office costs; phone, internet, printing,   sundries, admin services | £                                                                                          900.00 | £                      450.00 | £                 450.00 | Small equipment and materials
Events: meetings, focus groups, large   showings (cinema hire) | £                                                                                       1,400.00 | £                      200.00 | £              1,200.00 | Trips/outings/activities/residential   costs
Software development | £                                                                                       3,000.00 | £                   2,000.00 | £              1,000.00 | Sessional   staff costs
  |   |   |   |  
Total Expenditure | £                                                                                     44,283.57 |   |   |  

and the totals by catagory are: 


Catagory | Year 1 | Year 2 | Total
-- | -- | -- | --
Large   equipment (over £250) | 1800 | 500 | 2300
Other   staffing costs (recruitment/training/travel) | 600 | 200 | 800
Project   costs | 1020 | 1470 | 2490
Salary   expenditure (including National Insurance and pension) | 20502.51 | 12891.06 | 33393.57
Sessional   staff costs | 2000 | 1000 | 3000
Small   equipment and materials | 450 | 450 | 900
Trips/outings/activities/residential   costs | 200 | 1200 | 1400

**Comment by joereddington-public** [comment]
![screen shot 2018-09-13 at 22 21 43](https://user-images.githubusercontent.com/40637406/45516581-6e20dd80-b7a3-11e8-85ca-79ee8acc875e.png)
