### ISSUE TITLE
Reapply to Arts council

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#59]
We have a [fairly long history](http://equalitytime.co.uk/6217/2018/03/27/reviewers-wanted-for-battlecry/) submitting the same project to the arts council and improving the submission each time.   We've had quite a long gap since last time we sent an application and during that gap we had [a professional look](https://github.com/eQualityTime/Public/issues/12) at the parts of the application on which we were particularly weak. 

Some notes: 

* We've started naming the submissions alphabetically because the arts council portal was getting crowded.  This one is "Discord", the previous one was "Codex" (all files in resources).
* Some of this happened offline because the consultant didn't want their thoughts made public.

# Resources 
* [Application portal](https://applications.artscouncil.org.uk/viewFormlet_Details.jsf) 
* [CODEX submission.pdf](https://github.com/eQualityTime/Public/files/2624666/CODEX.submission.pdf)
* [CODEX  arts project.docx](https://github.com/eQualityTime/Public/files/2624667/CODEX.arts.project.docx)
* [CODEX TOOMANYCOOKS Audience Development Plan.docx](https://github.com/eQualityTime/Public/files/2624668/CODEX.TOOMANYCOOKS.Audience.Development.Plan.docx)
* [CODEX TOOMANYCOOKS budget.xlsx](https://github.com/eQualityTime/Public/files/2624669/CODEX.TOOMANYCOOKS.budget.xlsx)

# Plan
- [x] create new files 
- [x] Look at the model answers and see rewrite existing ones 
- [x] Update budget and other files
- [x] submit.

**Comment by joereddington** [comment]
[CODEX submission.pdf](https://github.com/eQualityTime/Public/files/2624666/CODEX.submission.pdf)
[CODEX  arts project.docx](https://github.com/eQualityTime/Public/files/2624667/CODEX.arts.project.docx)
[CODEX TOOMANYCOOKS Audience Development Plan.docx](https://github.com/eQualityTime/Public/files/2624668/CODEX.TOOMANYCOOKS.Audience.Development.Plan.docx)
[CODEX TOOMANYCOOKS budget.xlsx](https://github.com/eQualityTime/Public/files/2624669/CODEX.TOOMANYCOOKS.budget.xlsx)

**Comment by joereddington-public** [comment]
Started a new project. Called it "discord". I've got through the eligability checker and now need to get the turnover from last full finantial year.  Also the documents on model answers. Next step to be done offline.

**Comment by joereddington-public** [comment]
Answers to rewrite: 

Tell us about your, and your partners', recent experience in managing similar types of projects.
You can use up to 1500 characters to answer this.
This is a single organisation application and we take full responsbility for it:
All members of the eQuality Time team have extensive experience of both event management and the novel writing process. Significantly, eQuality Time has produced over 80 novels with groups from schools, universities, hospises, and special units, developing the software and horning the techniques to be used in the BATTLECRY project, which will our first aimed at commercial and critical success (the others were aimed at writer development).
Regarding the media facing aspects of the work, we have dealt with a variety of significant media events in the past 12 months including being the winner of the £50,000 Nesta Inclusive Prize and being chosen as one of the 2016 Nominet 100 projects for social good. We have also budgeted for extra resources from a media agency we have close links with.
Our links with publishers and agents are evidenced by the recommendation letter attached to this application.


_

> Tell us how you will manage the budget for this project, and about your previous experience of managing budgets.
> You can use up to 1500 characters to answer this.

_
Equality Time was awarded grant funding of £34k in 2014 and £50k in 2015 and receives an increasing amount of earned income as projects mature and become sustainable.
Equality Time has a mix of restricted and unrestricted funding. Overhead costs are clearly identified and we aim to apply 'full cost recovery’ in all cases. Core costs are apportioned to projects and 20% of invoiced income is allocated to overheads.
Prior to joining eQuality Time our treasurer had experience of budgeting in the social enterprise sector, having founded and run West Lancs Positive Living (charity) EnDevA (CIC) and Phil the Box (Co ltd by guarantee) and is currently legal and financial officer with Burscough Parish Council managing an income of over £100,000 pa which is subject to strict budget controls and external audit. Accounts are prepared using a spreadsheet, and all income and expenditure is allocated to a budget heading and to a fund. A bank reconciliation and analysis of variation from budget is completed monthly so that we always know that expenditure is on track. All expenditure decisions are decided at committee meetings and all payments require two signatories. Financial controls are robust.
At the outset, Equality Time invested in the services of an accountant (TLL) who has specialist knowledge of the third sector, so that as we grow we are confident that our accounting systems are capable of growing with us and that we always have access to sound advice.

**Comment by joereddington** [comment]
Doing this now.  Have taken the consultants recommendations and have rewritten (some for 'insert fact there' and some for length) 

Now for the painful gant chart bits.

**Comment by joereddington** [comment]
Done! The final version is: 
[export-1.pdf](https://github.com/eQualityTime/Public/files/2906108/export-1.pdf)
